name: reuse
on: 
  workflow_call:
    inputs:
      name: 
        description: Enter the name
        required: true
        default: "guest"
        type: string
jobs:
  greetings:
    runs_on: ubuntu-latest
    steps:
      - name: Greeting message
        run: echo "Hi ${{ inputs.name }} Welcome"
